services:
  # Service Discovery Registry
  service-registry:
    build:
      context: .
      dockerfile: fr0g-ai-registry/Dockerfile
    ports:
      - "8500:8500"
    environment:
      - REGISTRY_PORT=8500
      - REGISTRY_HOST=0.0.0.0
    networks:
      - fr0g-ai-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8500/health"]
      interval: 30s
      timeout: 10s
      retries: 3


  # AI Identity & Persona Service
  fr0g-ai-aip:
    build:
      context: .
      dockerfile: fr0g-ai-aip/Dockerfile
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      - REGISTRY_URL=http://service-registry:8500
      - SERVICE_NAME=fr0g-ai-aip
      - SERVICE_ID=aip-001
      - HTTP_PORT=8080
      - GRPC_PORT=9090
      - STORAGE_TYPE=file
      - FR0G_STORAGE_TYPE=file
      - FR0G_DATA_DIR=/app/data
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - GRPC_ENABLE_REFLECTION=${GRPC_ENABLE_REFLECTION:-false}
      - ENVIRONMENT=${ENVIRONMENT:-production}
    volumes:
      - aip_data:/app/data
      - ./logs:/app/logs
    depends_on:
      - service-registry
    networks:
      - fr0g-ai-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # AI Bridge Service
  fr0g-ai-bridge:
    build:
      context: .
      dockerfile: fr0g-ai-bridge/Dockerfile
    ports:
      - "8082:8082"
      - "9092:9092"
    environment:
      - REGISTRY_URL=http://service-registry:8500
      - SERVICE_NAME=fr0g-ai-bridge
      - SERVICE_ID=bridge-001
      - HTTP_PORT=8082
      - GRPC_PORT=9092
      - OPENWEBUI_BASE_URL=${OPENWEBUI_BASE_URL:-http://openwebui:3000}
      - OPENWEBUI_API_KEY=${OPENWEBUI_API_KEY}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - AIP_GRPC_ENDPOINT=fr0g-ai-aip:9090
    volumes:
      - bridge_config:/app/config
      - ./logs:/app/logs
    depends_on:
      - service-registry
    networks:
      - fr0g-ai-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # AI Master Control (Cognitive Engine)
  fr0g-ai-master-control:
    build:
      context: .
      dockerfile: fr0g-ai-master-control/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - REGISTRY_URL=http://service-registry:8500
      - SERVICE_NAME=fr0g-ai-master-control
      - SERVICE_ID=mcp-001
      - HTTP_PORT=8081
      - STORAGE_TYPE=file
      - DATA_DIR=/app/data
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - MCP_LEARNING_ENABLED=${MCP_LEARNING_ENABLED:-true}
      - MCP_SYSTEM_CONSCIOUSNESS=${MCP_SYSTEM_CONSCIOUSNESS:-true}
      - MCP_EMERGENT_CAPABILITIES=${MCP_EMERGENT_CAPABILITIES:-true}
      - MCP_MAX_CONCURRENT_WORKFLOWS=${MCP_MAX_CONCURRENT_WORKFLOWS:-10}
    volumes:
      - mcp_data:/app/data
      - ./logs:/app/logs
    depends_on:
      - service-registry
    networks:
      - fr0g-ai-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # AI Input/Output Processing Service
  fr0g-ai-io:
    build:
      context: .
      dockerfile: fr0g-ai-io/Dockerfile
    ports:
      - "8083:8083"
      - "9093:9093"
    environment:
      - REGISTRY_URL=http://service-registry:8500
      - SERVICE_NAME=fr0g-ai-io
      - SERVICE_ID=io-001
      - HTTP_PORT=8083
      - GRPC_PORT=9093
      - MCP_GRPC_ENDPOINT=fr0g-ai-master-control:8081
      - LOG_LEVEL=${LOG_LEVEL:-info}
      # SMS Configuration
      - SMS_ENABLED=${SMS_ENABLED:-true}
      - SMS_PROVIDER=${SMS_PROVIDER:-google_voice}
      - SMS_API_KEY=${SMS_API_KEY}
      - SMS_API_SECRET=${SMS_API_SECRET}
      # Voice Configuration
      - VOICE_ENABLED=${VOICE_ENABLED:-true}
      - VOICE_PROVIDER=${VOICE_PROVIDER:-google_voice}
      - VOICE_API_KEY=${VOICE_API_KEY}
      - VOICE_API_SECRET=${VOICE_API_SECRET}
      # IRC Configuration
      - IRC_ENABLED=${IRC_ENABLED:-true}
      - IRC_SERVER=${IRC_SERVER:-irc.libera.chat}
      - IRC_PORT=${IRC_PORT:-6697}
      - IRC_USE_SSL=${IRC_USE_SSL:-true}
      # ESMTP Configuration
      - ESMTP_ENABLED=${ESMTP_ENABLED:-true}
      - ESMTP_PORT=${ESMTP_PORT:-2525}
      - ESMTP_HOST=${ESMTP_HOST:-0.0.0.0}
      # Discord Configuration
      - DISCORD_ENABLED=${DISCORD_ENABLED:-true}
    volumes:
      - io_data:/app/data
      - ./logs:/app/logs
    depends_on:
      - service-registry
      - fr0g-ai-master-control
    networks:
      - fr0g-ai-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: Add OpenWebUI for complete AI chat interface
  # Uncomment to enable full AI chat capabilities
  # openwebui:
  #   image: ghcr.io/open-webui/open-webui:main
  #   container_name: fr0g-ai-openwebui
  #   ports:
  #     - "3000:8080"
  #   environment:
  #     - OLLAMA_BASE_URL=http://ollama:11434
  #     - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY:-your-secret-key}
  #   volumes:
  #     - openwebui_data:/app/backend/data
  #   restart: unless-stopped
  #   networks:
  #     - fr0g-ai-network

networks:
  fr0g-ai-network:
    driver: bridge

volumes:
  aip_data:
    driver: local
  bridge_config:
    driver: local
  mcp_data:
    driver: local
  io_data:
    driver: local
  openwebui_data:
    driver: local
  registry-data:
    driver: local
