// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: proto/bridge.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Fr0GAiBridgeService_HealthCheck_FullMethodName    = "/fr0g.ai.bridge.v1.Fr0gAiBridgeService/HealthCheck"
	Fr0GAiBridgeService_ChatCompletion_FullMethodName = "/fr0g.ai.bridge.v1.Fr0gAiBridgeService/ChatCompletion"
)

// Fr0GAiBridgeServiceClient is the client API for Fr0GAiBridgeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Fr0gAiBridgeService provides bridge functionality between fr0g.ai and external AI systems
type Fr0GAiBridgeServiceClient interface {
	// HealthCheck performs a health check
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	// ChatCompletion processes chat completion requests
	ChatCompletion(ctx context.Context, in *ChatCompletionRequest, opts ...grpc.CallOption) (*ChatCompletionResponse, error)
}

type fr0GAiBridgeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFr0GAiBridgeServiceClient(cc grpc.ClientConnInterface) Fr0GAiBridgeServiceClient {
	return &fr0GAiBridgeServiceClient{cc}
}

func (c *fr0GAiBridgeServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, Fr0GAiBridgeService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fr0GAiBridgeServiceClient) ChatCompletion(ctx context.Context, in *ChatCompletionRequest, opts ...grpc.CallOption) (*ChatCompletionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatCompletionResponse)
	err := c.cc.Invoke(ctx, Fr0GAiBridgeService_ChatCompletion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Fr0GAiBridgeServiceServer is the server API for Fr0GAiBridgeService service.
// All implementations must embed UnimplementedFr0GAiBridgeServiceServer
// for forward compatibility.
//
// Fr0gAiBridgeService provides bridge functionality between fr0g.ai and external AI systems
type Fr0GAiBridgeServiceServer interface {
	// HealthCheck performs a health check
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	// ChatCompletion processes chat completion requests
	ChatCompletion(context.Context, *ChatCompletionRequest) (*ChatCompletionResponse, error)
	mustEmbedUnimplementedFr0GAiBridgeServiceServer()
}

// UnimplementedFr0GAiBridgeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFr0GAiBridgeServiceServer struct{}

func (UnimplementedFr0GAiBridgeServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedFr0GAiBridgeServiceServer) ChatCompletion(context.Context, *ChatCompletionRequest) (*ChatCompletionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChatCompletion not implemented")
}
func (UnimplementedFr0GAiBridgeServiceServer) mustEmbedUnimplementedFr0GAiBridgeServiceServer() {}
func (UnimplementedFr0GAiBridgeServiceServer) testEmbeddedByValue()                             {}

// UnsafeFr0GAiBridgeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Fr0GAiBridgeServiceServer will
// result in compilation errors.
type UnsafeFr0GAiBridgeServiceServer interface {
	mustEmbedUnimplementedFr0GAiBridgeServiceServer()
}

func RegisterFr0GAiBridgeServiceServer(s grpc.ServiceRegistrar, srv Fr0GAiBridgeServiceServer) {
	// If the following call pancis, it indicates UnimplementedFr0GAiBridgeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Fr0GAiBridgeService_ServiceDesc, srv)
}

func _Fr0GAiBridgeService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Fr0GAiBridgeServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fr0GAiBridgeService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Fr0GAiBridgeServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fr0GAiBridgeService_ChatCompletion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatCompletionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Fr0GAiBridgeServiceServer).ChatCompletion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fr0GAiBridgeService_ChatCompletion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Fr0GAiBridgeServiceServer).ChatCompletion(ctx, req.(*ChatCompletionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Fr0GAiBridgeService_ServiceDesc is the grpc.ServiceDesc for Fr0GAiBridgeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Fr0GAiBridgeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fr0g.ai.bridge.v1.Fr0gAiBridgeService",
	HandlerType: (*Fr0GAiBridgeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _Fr0GAiBridgeService_HealthCheck_Handler,
		},
		{
			MethodName: "ChatCompletion",
			Handler:    _Fr0GAiBridgeService_ChatCompletion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/bridge.proto",
}
