# fr0g.ai ESMTP Threat Vector Interceptor Configuration
# "The intelligent front desk for email communications"

# Server Configuration
host: "0.0.0.0"
port: 2525
tls_port: 2465
hostname: "fr0g-ai-interceptor.local"

# Message Limits
max_message_size: 10485760  # 10MB in bytes
timeout: "5m"

# Community Review Settings
community_topic: "email-threat-analysis"
persona_count: 5
review_timeout: "2m"
required_consensus: 0.7

# TLS Configuration (for secure email reception)
enable_tls: false
cert_file: "/etc/ssl/certs/fr0g-ai.crt"
key_file: "/etc/ssl/private/fr0g-ai.key"

# Threat Analysis Settings
threat_analysis:
  enable_attachment_scanning: true
  enable_content_analysis: true
  enable_sender_reputation: true
  quarantine_suspicious: true
  
# Logging
log_level: "info"
log_format: "json"

# Performance Tuning
max_concurrent_connections: 100
connection_timeout: "30s"
read_timeout: "10s"
write_timeout: "10s"
