# fr0g-ai-bridge Configuration Example
# Copy this file to config.yaml and modify as needed

server:
  # HTTP REST API server configuration
  http_port: 8080
  # gRPC server configuration  
  grpc_port: 9090
  # Host to bind to (0.0.0.0 for all interfaces)
  host: "0.0.0.0"

openwebui:
  # OpenWebUI base URL
  base_url: "http://localhost:3000"
  # OpenWebUI API key (get from Settings > Account in OpenWebUI)
  api_key: ""
  # Request timeout in seconds
  timeout: 30

logging:
  # Log level: debug, info, warn, error
  level: "info"
  # Log format: json, text
  format: "json"
# fr0g-ai-bridge Configuration Example
# Copy this file to config.yaml and customize for your environment

server:
  http_port: 8080
  grpc_port: 9090
  host: "0.0.0.0"

openwebui:
  base_url: "http://localhost:3000"
  api_key: ""  # Set your OpenWebUI API key here
  timeout: 30  # Request timeout in seconds

logging:
  level: "info"    # debug, info, warn, error
  format: "json"   # json, text

# Security settings
security:
  enable_cors: true
  allowed_origins: ["*"]  # Change to specific domains in production
  rate_limit_requests_per_minute: 60
  require_api_key: false  # Set to true in production
  allowed_api_keys: []    # Add your API keys here when require_api_key is true
  enable_reflection: true # Set to false in production

# Monitoring settings
monitoring:
  enable_metrics: true
  metrics_port: 8082
  health_check_interval: 30
  enable_tracing: false
